### ISSUE TITLE
Where to add API key ?

### ISSUE THREAD

**Issue by flagos** [emacs-openai/codegpt#16]
Hi,

The documentation states that:
```
Copy the key and paste into the 'API Key' field under the 'openai' custom group settings.
```

It's not really obvious to me what I should do here. I got my API key from the url, but I've no idea what this openai custom group settings. Can you  please elaborate ?

**Comment by jcs090218** [comment]
This package relies on [openai.el](https://github.com/emacs-openai/openai), please see this section https://github.com/emacs-openai/openai#-usage.

> openai custom group settings

The wording should probably be change by now. The older version was using `defcustom`, and it's bad practice see https://github.com/emacs-openai/openai/issues/5#issue-1611978573.

**Comment by flagos** [comment]
Thank you, it's working well now.
