### ISSUE TITLE
delete this issue - MISTAKE

### ISSUE THREAD

**Issue by grpgrp** [emacs-openai/codegpt#17]
wrong repo

**Comment by grpgrp** [comment]
The new steerable versions are `gpt-4-0613` and `gpt-3.5-turbo-0613`.

The longer context one is `gpt-3.5-turbo-16k` but I think we will do better with the steerable version above.  Eventually I am sure they will offer both 4K and steerable in a named model.

So I have switched us to `gpt-3.5-turbo-0613` for now.

**Comment by jcs090218** [comment]
👍
